### ISSUE TITLE
🐞 UI 보충

### ISSUE THREAD

**Issue by iQuQi** [boostcampwm2023/web09-MagicConch#281]
## Description
설명을 작성하세요

## How to reproduce it
버그를 재현하는 방법을 작성하세요

## Todo
- [x] 사이드바 위로 올라오는 문제
- [x] 캠 컴포넌트 회색일 때 내부 선 진하게 변경 & 기본 프사일 때 버튼 색 변경
- [x] Select option 리스트가 비었을 때 처리
- [x] select collapse content z-index 올리기 (현재 select가 다른 select에 가림)
- [x] 프로필 팝업 UI 다듬기
- [x] 프로필 편집 들어갈 때 로딩 시간동안 기본 이미지 보여주기 (현재 비어있는 상태로 보여짐)
- [x] 원형 버튼 사이즈 large 타입 추가하기
- [x] 캠 끄면 검은 화면으로 보이는 문제 해결하기

## ETC
기타 사항
